"""Flujo completo con modelos reales y PostgreSQL:
registrar persona -> registrar rostro -> reconocer -> evento -> asistencia."""

import uuid
from datetime import UTC, datetime, timedelta

import pytest
from alembic.util.exc import AutogenerateDiffsDetected

from alembic import command
from app.core.exceptions import FaceConflictError
from app.database.models import AttendanceType, RecognitionEvent
from app.database.repositories.attendance_repository import AttendanceRepository
from app.database.repositories.person_repository import PersonRepository
from app.services.attendance_service import AttendanceService
from app.services.cooldown import RecognitionCooldown
from app.services.event_service import RecognitionEventService
from app.services.gallery_service import GalleryService
from tests.conftest import load_fixture, side_by_side
from tests.db_fixtures import alembic_config


def test_models_match_migrations(db_engine, test_database_url):
    try:
        command.check(alembic_config(test_database_url))
    except AutogenerateDiffsDetected as exc:  # pragma: no cover
        pytest.fail(f"Los modelos no coinciden con las migraciones: {exc}")


def test_enroll_recognize_record(db_session, pipeline, cipher):
    people = PersonRepository(db_session)
    obama = people.create("Barack", "Obama")
    harris = people.create("Kamala", "Harris")

    gallery = GalleryService(pipeline, cipher)
    gallery.enroll_face(db_session, obama.id, load_fixture("obama_2012.jpg"))
    gallery.enroll_face(db_session, harris.id, load_fixture("harris.jpg"))
    assert gallery.reload(db_session) == 2

    now = datetime(2026, 9, 22, 11, 0, tzinfo=UTC)
    events = RecognitionEventService(RecognitionCooldown(10), camera_id="entrada")
    attendance = AttendanceService(timedelta(minutes=10), tz=UTC)

    scene = side_by_side("obama_2009.jpg", "biden.jpg", "harris.jpg")
    results = [a.recognition for a in pipeline.process(scene)]
    processed = events.process(db_session, results, now)
    for result in processed.fresh:
        if result.recognized:
            attendance.register(db_session, uuid.UUID(result.person_id), result.confidence, now)

    stored = db_session.query(RecognitionEvent).all()
    assert sorted((e.person_id is not None) for e in stored) == [False, True, True]
    records = AttendanceRepository(db_session).list()
    assert {r.person_id for r in records} == {obama.id, harris.id}
    assert all(r.type is AttendanceType.ENTRY for r in records)

    # Una persona desactivada deja de ser reconocida tras recargar.
    people.update(obama.id, active=False)
    gallery.reload(db_session)
    [analysis] = pipeline.process(load_fixture("obama_2009.jpg"))
    assert not analysis.recognition.recognized


def test_enrollment_rejects_inconsistent_samples(db_session, pipeline, cipher):
    people = PersonRepository(db_session)
    obama = people.create("Barack", "Obama")
    harris = people.create("Kamala", "Harris")
    gallery = GalleryService(pipeline, cipher)
    gallery.enroll_face(db_session, obama.id, load_fixture("obama_2012.jpg"))

    # Otra foto de la misma persona: aceptada.
    gallery.enroll_face(db_session, obama.id, load_fixture("obama_2009.jpg"))
    # Foto de otra persona cargada por error como Obama: rechazada.
    with pytest.raises(FaceConflictError, match="no coincide"):
        gallery.enroll_face(db_session, obama.id, load_fixture("biden.jpg"))
    # Foto de Obama cargada como Harris (que no tiene muestras): rechazada.
    with pytest.raises(FaceConflictError, match="Barack Obama"):
        gallery.enroll_face(db_session, harris.id, load_fixture("obama_2009.jpg"))

    assert PersonRepository(db_session).embedding_counts() == {obama.id: 2}
