"""initial schema

Revision ID: 1cc0f89b3ca2
Revises: 
Create Date: 2026-09-22 16:16:17.702453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cc0f89b3ca2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_persons')),
    sa.UniqueConstraint('email', name=op.f('uq_persons_email'))
    )
    op.create_table('attendance_records',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('ENTRY', 'EXIT', name='attendance_type'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_attendance_records_person_id_persons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_records'))
    )
    op.create_index('ix_attendance_records_person_id_created_at', 'attendance_records', ['person_id', 'created_at'], unique=False)
    op.create_table('face_embeddings',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_face_embeddings_person_id_persons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_face_embeddings'))
    )
    op.create_index(op.f('ix_face_embeddings_model_version'), 'face_embeddings', ['model_version'], unique=False)
    op.create_index(op.f('ix_face_embeddings_person_id'), 'face_embeddings', ['person_id'], unique=False)
    op.create_table('recognition_events',
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('recognized', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('camera_id', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_recognition_events_person_id_persons'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recognition_events'))
    )
    op.create_index('ix_recognition_events_created_at', 'recognition_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_recognition_events_person_id'), 'recognition_events', ['person_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recognition_events_person_id'), table_name='recognition_events')
    op.drop_index('ix_recognition_events_created_at', table_name='recognition_events')
    op.drop_table('recognition_events')
    op.drop_index(op.f('ix_face_embeddings_person_id'), table_name='face_embeddings')
    op.drop_index(op.f('ix_face_embeddings_model_version'), table_name='face_embeddings')
    op.drop_table('face_embeddings')
    op.drop_index('ix_attendance_records_person_id_created_at', table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_table('persons')
    # drop_table no elimina el tipo ENUM de PostgreSQL.
    sa.Enum(name='attendance_type').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
